version: "3"

networks:
  backend:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    logging:
      driver: none
    networks:
      - backend
    ports:
      - 27018:27017
    volumes:
      - ~/mongo/data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27018/
    depends_on:
      - mongo
    logging:
      driver: none
    networks:
      - backend

  authorization:
    image: therealguriev/service-authorization:87801bf9f278681ad1458401d1a97f8f84169a3e
    restart: unless-stopped
    depends_on:
      - mongo
    logging:
      driver: none
    networks:
      - backend
    environment:
      NITRO_MONGO_URI: "mongodb://root:example@mongo:27018/"
      NITRO_SECRET: "secret"
    ports:
      - 3000:3000
